In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [4]:
HP_df = pd.read_csv("data/train.csv")
HP_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
# Filter out the non-numerical columns
HP_df = HP_df.select_dtypes(include = ["number"])
HP_df = HP_df.dropna()
#HP_df=HP_df.drop(['Id'],axis=1)
# Prepare train/test split in our train data (no y in test)
split = int(0.8 * len(HP_df))

# Split the DataFrame into training and testing sets
train_df = HP_df[:split].dropna()
test_df = HP_df[split:].dropna()

display(train_df)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,1159,20,92.0,11932,8,5,2007,2008,186.0,0,...,0,24,0,0,0,0,0,6,2008,235128
1159,1160,60,76.0,9120,6,6,1974,1974,270.0,442,...,0,69,0,0,0,0,0,7,2008,185000
1160,1161,160,24.0,2280,6,5,1978,1978,0.0,311,...,26,0,0,0,0,0,0,7,2010,146000
1162,1163,20,109.0,8724,5,5,1968,1968,0.0,492,...,0,0,0,0,0,0,0,5,2007,129000
1163,1164,90,60.0,12900,4,4,1969,1969,0.0,1198,...,120,0,0,0,0,0,0,1,2008,108959

In [ ]:
# Model Expression:
#   L2 Ridge Regression - y = X\beta + error, where \beta = (X^T@X + \lambda@I)^-1 @ (X^T @ Y)
#   Linear Regression (single-var) - y = \beta1*x+ \beta_0, where \beta = cov(x,y)/ var(x)

# Prepare X-matrix and y vector
X = train_df.drop(columns=['SalePrice'])
y = train_df['SalePrice']



# Calculate the regular LR beta
XT_x = np.dot(X.T, X)
XT_y = np.dot(X.T, y)

beta = np.dot(np.linalg.inv(XT_x), XT_y)


# Ridge Regression beta calculation
lambda_ = 1e6# our penalty
I = np.eye(X.shape[1])
beta_ridge = np.dot(np.linalg.inv(XT_x + lambda_ * I), XT_y)


print("Beta coefficients for ridge regression:\n", beta_ridge)
print("Beta coefficients for regular regression:\n", beta)

Beta coefficients for ridge regression:
 [   0.31363497  -58.21495415   -4.84067132    0.59691121   16.68535383
    3.54278653   84.36055052   63.36597606   42.96906183   29.21371049
   -0.92875039   10.56606766   38.85102776   20.78732685   32.92895514
  -13.61105773   40.10522426    0.34955643   -0.31933354    1.95186205
    1.45729519   -5.59399857   -1.88958823    0.27017502    3.12615005
   10.93557277    2.10028144   81.62149387   36.22909365   48.85405749
  -46.87525485   -7.49153925   51.69214148  -16.03325918  -12.34416303
   -3.67998984 -168.80698985]
Beta coefficients for regular regression:
 [ 2.52889135e+04 -1.75461503e+05  1.29723473e+05 -1.65541421e+02
 -4.47134211e+05  6.54330705e+06  1.63047444e+05 -1.83660196e+05
 -1.11269760e+03  2.58760774e+16  2.58760774e+16  2.58760774e+16
 -2.58760774e+16 -1.40800000e+03 -1.66400000e+03 -2.17600000e+03
  2.04800000e+03  1.70439557e+03 -1.39352058e+03  3.64946488e+03
  1.57264499e+03 -1.34605319e+04 -2.54195392e+04  7.68124436e+03
  3.63080920e+03 -3.50105798e+01  5.34081115e+03  3.73932096e+01
  1.52534343e+01 -1.56159175e+00  3.36162135e+00 -2.04878466e+01
  6.01423467e+01 -5.17590531e+01 -7.01255199e+00 -7.97624931e+02
 -5.01870173e+02]

'\nReference: https://online.stat.psu.edu/stat857/node/155/\n'

In [7]:
# Compare the betas with metrics

### Ridge ###
pos_mask = beta_ridge > 0

test_X = test_df.drop(columns=['SalePrice'])
test_X = test_X.loc[:, pos_mask]

test_y = test_df['SalePrice']

y = np.dot(beta_ridge[pos_mask], test_X.values.T) + (np.mean(test_y) - np.dot(beta_ridge[pos_mask],
                                                                              np.mean(test_X.values, axis=0)))

test_y_values = test_y.values  # convert test_y to a numpy array

SSR = np.sum((y - test_y_values)**2)
SST = np.sum((test_y_values - np.mean(test_y_values))**2)

R2 = 1 - SSR / SST
print("ridge-beta R^2: ", R2)

### Use overallQual as the only beta: manual ###
train_X = train_df.drop(columns=['SalePrice'])
train_X = train_X[["OverallQual"]].values
train_y = train_df['SalePrice'].values

test_y = test_df['SalePrice']
test_X = test_df["OverallQual"]

cov_xy = 0
var_x = 0
if len(train_X ) == len(train_y ):
    for i in range(len(train_X)):

        cov_xy += (train_X[i] - np.mean(train_X))*(train_y[i] - np.mean(train_y))
        var_x += pow((train_X[i] - np.mean(train_X)),2)

m = cov_xy / var_x
b = np.mean(train_y) - (m*np.mean(train_X)) 

y = m*test_X + b
y = np.array(y[:len(test_y)])

test_y_values = test_y.values

SSR = np.sum((y - test_y_values)**2)
SST = np.sum((test_y_values- np.mean(test_y_values))**2)

R2 = 1 - SSR / SST

print("single beta R^2: ", R2)

ridge-beta R^2:  0.33660016988488084
single beta R^2:  0.5860038832202537

In [8]:
### Use overallQual as the only beta: library ###
X = HP_df.drop(columns=['SalePrice'])
X = X[["OverallQual"]]
Y= HP_df['SalePrice']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state= 42)



model = LinearRegression()
model.fit(X_train, Y_train)

test_predictions = model.predict(X_test)
train_predictions = model.predict(X_train)
# call the metrics
mse = mean_squared_error(Y_test, test_predictions)
print("OverallQaul RMSE:", np.sqrt(mse))
r2_test= r2_score(Y_test, test_predictions)
print("R2 - test:", r2_test)

r2_train = r2_score(Y_train, train_predictions)
print("R2 - train:", r2_train)

OverallQaul RMSE: 58157.8848953289
R2 - test: 0.5711674996177418
R2 - train: 0.6544111480987971

In [9]:
### Choosing several Ridge lambda to determine the  most probable regressors ###
lambda_values = [10**(i) for i in range(-2, 7)]
ridge_coefficients = []
ridge_rmse_calc = {}
for lambda_ in lambda_values:
    I = np.eye(X.shape[1])
    beta_ridge = np.dot(np.linalg.inv(XT_x + lambda_ * I), XT_y)
    ridge_coefficients.append(beta_ridge)

ridge_coefficients = np.array(ridge_coefficients)

for i in range(len(ridge_coefficients)):
    sorted_indices = np.argsort(ridge_coefficients[i])[::-1]
    top_5_indices = sorted_indices[:5]
    top_5_columns = HP_df.columns[top_5_indices]
    ridge_rmse_calc[lambda_values[i]] = top_5_columns.tolist()
    print(f"\nLambda = {lambda_values[i]}")
    print("Top 5 coefficients:", ridge_coefficients[i][top_5_indices])
    print("Top 5 columns:", top_5_columns.tolist())

Lambda = 0.01
Top 5 coefficients: [664704.         664576.         664448.          43648.
  11299.95775315]
Top 5 columns: ['BsmtFinSF1', 'BsmtUnfSF', 'BsmtFinSF2', 'GrLivArea', 'LotFrontage']

Lambda = 0.1
Top 5 coefficients: [1925109.7686853   282688.          282528.          281952.
   67424.80793856]
Top 5 columns: ['OverallCond', 'BsmtUnfSF', 'BsmtFinSF1', 'BsmtFinSF2', 'LotFrontage']

Lambda = 1
Top 5 coefficients: [171929.25914308 105056.          10624.           8468.78531758
   7681.24435884]
Top 5 columns: ['OverallQual', 'TotalBsmtSF', 'GrLivArea', 'YearRemodAdd', 'TotRmsAbvGrd']

Lambda = 10
Top 5 coefficients: [164608.         164288.         164224.          63672.67451483
  38181.44693422]
Top 5 columns: ['BsmtUnfSF', 'BsmtFinSF1', 'BsmtFinSF2', 'OverallQual', 'MSSubClass']

Lambda = 100
Top 5 coefficients: [2141924.35190928 1103616.         1100032.         1096192.
  671905.75042011]
Top 5 columns: ['OverallQual', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'YearRemodAdd']

Lambda = 1000
Top 5 coefficients: [409536.          58504.78408719  42638.48018774   7681.2443597
   5340.81114781]
Top 5 columns: ['TotalBsmtSF', 'YearRemodAdd', 'OverallQual', 'TotRmsAbvGrd', 'GarageCars']

Lambda = 10000
Top 5 coefficients: [112601.75108153  78752.          78656.          78496.
  18455.4656608 ]
Top 5 columns: ['OverallCond', 'BsmtFinSF2', 'BsmtFinSF1', 'BsmtUnfSF', 'YearBuilt']

Lambda = 100000
Top 5 coefficients: [415177.75476775 176256.         132421.56496842  24800.47754941
   9152.        ]
Top 5 columns: ['OverallQual', 'TotalBsmtSF', 'OverallCond', 'YearRemodAdd', 'GrLivArea']

Lambda = 1000000
Top 5 coefficients: [303578.86980531 148256.          50962.11595955  25876.16054329
   7681.24435957]
Top 5 columns: ['OverallQual', 'TotalBsmtSF', 'OverallCond', 'YearRemodAdd', 'TotRmsAbvGrd']

In [10]:
### Using 'YearBuilt', the shrunk result, to test for our metrics ###
X = HP_df.drop(columns=['SalePrice'])
X = X[["YearBuilt"]]
Y= HP_df["SalePrice"]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state= 42)

model = LinearRegression()
model.fit(X_train, Y_train)

test_predictions = model.predict(X_test)
train_predictions = model.predict(X_train)

mse = mean_squared_error(Y_test, test_predictions)
print("YearBuilt RMSE:", np.sqrt(mse))
r2_test= r2_score(Y_test, test_predictions)
print("R2 - test:", r2_test)

r2_train = r2_score(Y_train, train_predictions)
print("R2 - train:", r2_train)

YearBuilt RMSE: 79971.14333922046
R2 - test: 0.18915639589647204
R2 - train: 0.2990255608694403

In [11]:

ridge_rmse_calc

{0.01: ['BsmtFinSF1', 'BsmtUnfSF', 'BsmtFinSF2', 'GrLivArea', 'LotFrontage'],
 0.1: ['OverallCond', 'BsmtUnfSF', 'BsmtFinSF1', 'BsmtFinSF2', 'LotFrontage'],
 1: ['OverallQual',
  'TotalBsmtSF',
  'GrLivArea',
  'YearRemodAdd',
  'TotRmsAbvGrd'],
 10: ['BsmtUnfSF', 'BsmtFinSF1', 'BsmtFinSF2', 'OverallQual', 'MSSubClass'],
 100: ['OverallQual', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'YearRemodAdd'],
 1000: ['TotalBsmtSF',
  'YearRemodAdd',
  'OverallQual',
  'TotRmsAbvGrd',
  'GarageCars'],
 10000: ['OverallCond', 'BsmtFinSF2', 'BsmtFinSF1', 'BsmtUnfSF', 'YearBuilt'],
 100000: ['OverallQual',
  'TotalBsmtSF',
  'OverallCond',
  'YearRemodAdd',
  'GrLivArea'],
 1000000: ['OverallQual',
  'TotalBsmtSF',
  'OverallCond',
  'YearRemodAdd',
  'TotRmsAbvGrd']}

In [12]:
### Check for the lowest RSME, R2 (trade-off)  ###

for lambda_, top_columns in ridge_rmse_calc.items():

    X = HP_df[top_columns]
    y = HP_df['SalePrice']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = LinearRegression()
    model.fit(X_train, y_train)

    test_predictions = model.predict(X_test)
    train_predictions = model.predict(X_train)

    # Evaluate the model
    rmse_train = np.sqrt(mean_squared_error(y_train, train_predictions))
    r2_train = r2_score(y_train, train_predictions)
    rmse_test = np.sqrt(mean_squared_error(y_test,test_predictions))
    r2_test = r2_score(y_test, test_predictions)


    print(f"test rmse: {rmse_test}")
    print(f"test R^2: {r2_test}")
    print("------------------------------")

test rmse: 50157.397152870624
test R^2: 0.6810368822602673
------------------------------
test rmse: 67622.50232200693
test R^2: 0.4202337100079554
------------------------------
test rmse: 45203.79536677573
test R^2: 0.7409281146598197
------------------------------
test rmse: 52057.36988499083
test R^2: 0.6564144190968639
------------------------------
test rmse: 51807.26201038286
test R^2: 0.6597079787743525
------------------------------
test rmse: 47446.90344545817
test R^2: 0.7145787963512268
------------------------------
test rmse: 65329.43247584665
test R^2: 0.4588866409077421
------------------------------
test rmse: 45348.91328907225
test R^2: 0.7392620456639872
------------------------------
test rmse: 47968.94900839958
test R^2: 0.7082634172055389
------------------------------

In [21]:
### Check Correlation Matrix for Consistency ###
%matplotlib inline

corr_matrix = HP_df.corr()
top10_features = corr_matrix.sum().sort_values(ascending=False).head(10).index
top10_corr_matrix = HP_df[top10_features].corr()



plt.figure(figsize=(10, 8))
sns.heatmap(top10_corr_matrix, annot=True)
plt.title('Correlation Matrix for Top 10 Features')
plt.tight_layout()
plt.savefig('figures/cor-matrix.png', dpi=300)
plt.close()